version: "3"

services:
  broadcaster:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: broadcaster
    image: thunder-broadcaster
    container_name: thunder-broadcaster
    env_file: env/.env-broadcaster
    volumes:
      - ./logs:/home/thunder/work/logs
    network_mode: "host"
    restart: always
