[tool.pytest.ini_options]
filterwarnings = ["ignore::FutureWarning"]

[tool.pyright]
include = ["src", "scripts", "tests", "app.py"]
pythonVersion = "3.9"
pythonPlatform = "Linux"
exclude = ["**/node_modules", "**/__pycache__", ".git"]
reportMissingImports = false
reportUnusedImport = false
reportUnusedVariable = false
reportDuplicateImport = false
reportUndefinedVariable = false

[tool.black]
line-length = 100
target-version = ["py39"]
fast = true

[tool.isort]
line_length = 100
profile = "black"
