[tool.pytest.ini_options]
filterwarnings = ["ignore::FutureWarning"]

[tool.pyright]
include = ["src", "scripts", "tests", "app"]
pythonVersion = "3.9"
pythonPlatform = "Linux"
exclude = ["**/node_modules", "**/__pycache__", ".git"]
reportMissingImports = false
reportUnusedImport = false
reportUnusedVariable = false
reportDuplicateImport = false
reportUndefinedVariable = false
reportTypedDictNotRequiredAccess = false

[tool.black]
line-length = 96
target-version = ["py39"]
fast = true

[tool.isort]
line_length = 96
profile = "black"

[tool.mypy]
ignore_missing_imports = true
