[tool.isort]
line_length = 100

[tool.pyright]
include = ["src", "tests", "app.py"]
pythonVersion = "3.9"
pythonPlatform = "Linux"
exclude = ["**/node_modules", "**/__pycache__", ".git"]

[tool.pytest.ini_options]
filterwarnings = ["ignore::FutureWarning"]
